### ISSUE TITLE
Create a single pack with all the community improvements

### ISSUE THREAD

**Issue by DesolationStone** [ncblakely/CataclysmEngineTweaks#3]
Not a real issue, but imho it would be nice and really easy to condense the:

- [SAAAfarVIEWmod](https://drive.google.com/file/d/124g6NeSmwWp4lrki809kScsKKxP9AW8H/view)
- [Max Lod mod](https://www.moddb.com/games/homeworld-cataclysm/downloads/max-lod1)
- [Disable NLIPS mod](https://www.moddb.com/games/homeworld-cataclysm/downloads/disable-nlips1)
- Cataclysm Engine Tweaks

In to a single package/zip (less than 2mb) and call it "Homeworld Cataclysm: Community Patch".

**Comment by ncblakely** [comment]
I was actually planning to integrate a few of these into CET as executable modifications so they don't conflict with other mods that touch the same files. Max LOD is already in, but the rest are not integrated yet.

**Comment by Talthos** [comment]
From what I recall, that NLIPS mod does not touch the distance scaling used for capital ship engine glow effects, which is controlled by entries like `trailScaleCap` and `trail2ScaleCap` in a capital ship's SHP file.

Incidentally, Homeworld 1 also used these variables for the engine glow scaling, but only Cataclysm had at least one helpful dev comment in one of the SHP files, to describe what the variable actually does:
`N-LIPS for engine glow -- should be same as N-Lips value`

Commenting out those entries will disable them, of course.

**Comment by ncblakely** [comment]
N-LIPS can now be turned off in the .ini. I won't be touching the view distance just yet since this has gameplay impacts.
