### ISSUE TITLE
Enable use of the /safeGL launch command through the CataclysmEngineTweaks.ini ?

### ISSUE THREAD

**Issue by Talthos** [ncblakely/CataclysmEngineTweaks#4]
To clarify: I get massive texture glitches when running the game (whether modified or otherwise) in OpenGL mode on Windows 10 (on a Sapphire Pulse RX 6700 non-XT 10 GB GPU), but launching the game with `/safeGL` set fixes this problem.

The `CataclysmEngineTweaks.ini` does not seem to present a method of setting `/safeGL`, but interestingly enough, creating a shortcut to the `cataclysm_loader.exe` and then setting `/safeGL` in the Target field fixes it, just like it would for a shortcut to the original game exe.

Being able to set it in the `CataclysmEngineTweaks.ini` would be more intuitive, however.

**Comment by ncblakely** [comment]
Yes, I can add this. The command line arguments sent to the loader are forwarded to the game, but if this is needed on some systems it'd certainly be more convenient to have it in the .ini.

I'd look into the root cause of the graphical corruption but unfortunately neither of the PCs I own repro this.

**Comment by Talthos** [comment]
To my understanding, newer AMD GPUs have trouble with older versions of OpenGL. The graphical corruption also occurs in the unmodified Cataclysm game when running in OpenGL mode, and it also occurs in Homeworld 1 in OpenGL mode (using `/safeGL` fixes texture corruption in HW1 as well).

My current GPU: AMD Sapphire Pulse RX 6700 non-XT 10 GB

AMD Adrenalin software version: 24.5.1

Let me know if additional hardware and/or software detail is needed to help reproduce the problem.

**Comment by ncblakely** [comment]
Added the shortcut in v0.12. In a future release, I may break out the individual toggles that the /safeGL command line modifies into separate options, so we can try to figure out what exactly is causing this bug. I do not have any AMD cards here so can't repro it myself.
